# Copyright (C) 2024 Delta Computational Technologies
# Build and test for GCC on linux 
name: buildAndTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    # checkout our repository
    - uses: actions/checkout@v4
    - name: install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: run cmake
      run: |
        cd unitTest
        cmake .
    - name: build tests
      run: |
        cd unitTest
        make
    - name: test
      run: |
        cd unitTest
        ./matrixTest

    #- run: cd {{github.workspace}}/unitTest
    #- run: ./matrixTest
    # go to unit test directory
    # - run: cd {{github.workspace}}/unitTest
    # run cmake
    #- run: cmake .
    # build the tests
    # - run: make
    # run the tests
    #- run: ./matrixTest
